#!/bin/bash

### "BACKUP" EVERYTHING (BLINDLY)
# also: can add additional custom related actions in a local config file
# intended application: symbolically link to this file from elsewhere
#    use: $(./backup)

# Copyright (C) (2019-?) Nicholas Hanson-Holtry
# See: The GNU General Public License

source ./backup-config

git add .
git commit -m "auto"
git push origin master
