#!/bin/bash

source ./note-config

DATE=$(date +"%Y%m%d")

CLASSES=($(ls -d ~/private/class/notes/$QUARTER/*/))
for i in ${!CLASSES[@]}; do
  CLASSES[$i]=$(basename ${CLASSES[$i]})
done

if (( "$#" == "0" )); then
  nano ~/private/general/notes/$DATE
elif (( "$#" > "1" )); then
  echo "too many arguments"
else
  FOUND=0
  for CLASS in "${CLASSES[@]}"; do
    if [ "$1" == "$CLASS" ]; then
      nano ~/private/class/notes/$QUARTER/$CLASS/$DATE
      FOUND=1
    fi
  done
  if (( $FOUND == 0 )); then
    echo "invalid argument"
  fi
fi
