#!/bin/bash

TIME=$(date +"%Y%m%d")

i=0
CLASSES=()
while read data; do
  if (("$i"=="0")); then
    QUARTER=$data
  else
    CLASSES+=($data)
  fi
  ((i++))
done < .note-config

if [ "$#" == "0" ]; then
  nano ~/private/general/notes/$TIME
elif (( "$#" > "1" )); then
  echo "too many arguments"
  echo $#
else
  FOUND=0
  for CLASS in "${CLASSES[@]}"; do
    if [ "$1" == "$CLASS" ]; then
      nano ~/private/class/notes/$QUARTER/pro/$TIME
      FOUND=1
    fi
  done
  if (($FOUND==0)); then
    echo "invalid argument"
  fi
fi
